config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, -> (u){ u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/github' => 'omniauth_callbacks#github'
  end

  resources :attachments, only: [:destroy]

  concern :votable do
    resources :votes, only: [:up_rating, :down_rating, :unvote] do
      post :up_rating, on: :collection
      post :down_rating, on: :collection
      post :unvote, on: :collection
    end
  end


  resources :questions, concerns: :votable do
    resources :comments, only: [:create]
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: [:create]
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get :search, to:'search#index'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include ElasticMyAnalyzer
  include EsHelper
  include Votable
  include Attachable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user

  has_many :attachments, as: :attachable

  validates :body, :title, presence: true

  after_create :author_subscribe
  

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  settings ES_SETTING do
  mappings dynamic: 'true' do
    indexes :title, type: 'text', analyzer: 'my_analyzer'
    indexes :body, type: 'text', analyzer: 'my_analyzer'
    indexes :searching, type: 'boolean'
  end
end

  def best_answer
    answers.where(best: true).first
  end
  private

  def author_subscribe
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end
  def show
    respond_with Question.find(params[:id])
  end
  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
require 'pry'
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :update, :edit, :destroy]
  before_action :build_answer, only: [:show]
  before_action :set_subscription, only: [:show]
  after_action :publish_question, only: [:create]
  respond_to :js, :json

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
     @question.update(question_params)
    respond_with @question
  end


  def destroy
    if current_user.id == @question.user_id
      respond_with(@question.destroy)
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast 'questions', ApplicationController.render(partial: 'questions/question', locals: { q: @question })
  end

  def question_params
    params.require(:question).permit(:id,:title, :body, attachments_attributes: [:file, :id, :_delete])
  end
  def set_subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_for @question do |f|

  = f.label :title
  br
  = f.text_field :title
  br
  = f.label :body, 'Text'
  br
  = f.text_area :body
  br
  p Attachments
  p
    = f.fields_for :attachments do |a|
  	   = render 'attachments/attachments_fields', f: a
  	   = link_to_add_association 'Add', f, :attachments, partial: 'attachments/attachments_fields'
  = f.submit 'Create'

app/views/questions/_question.html.slim
.questions-list
  = q.title
  p= link_to 'Show', question_path(q)

app/views/questions/edit.html.slim
= render  'form'

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path
- @questions.each do |q|
    = render 'question', q: q

app/views/questions/new.html.slim
= form_for @question do  |f|

  = f.label :title, 'Title'
  br
  = f.text_field :title
  br
  = f.label :body, 'Text'
  br
  = f.text_area :body
  br
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = render 'attachments/attachments_fields', f: a
      = link_to_add_association 'Add', f, :attachments, partial: 'attachments/attachments_fields'
  = f.submit 'Create'

app/views/questions/show.html.slim
.question
  h1= @question.title
  p= @question.body
  = render partial: 'votes/vote', locals: { type: 'question', votable: @question }
  ul
  -@question.attachments.each do |a|
      li id="attachment-id-#{a.id}"
      li= link_to a.file.identifier, a.file.url
      br
       - if user_signed_in? && current_user.author_of?(@question)
       =link_to 'Delete', attachment_path(a), method: :delete, remote: true

  - if user_signed_in? && current_user.author_of?(@question)
    p = link_to 'Remove', question_path, method: :delete
    p = link_to 'Edit question', '', class: 'edit-question-link'
    p
.subscriptions
    - if can?(:destroy, @subscription)
      = link_to 'Unsubscribe', subscription_path(@subscription.id), class: 'unsubscribe-question-link', method: :delete, remote: true
    - else
      = link_to 'Subscribe', question_subscriptions_path(@question), class: 'subscribe-question-link', method: :post, remote: true
.edit_question
      = form_for @question, remote: true do |f|
        = f.label :title
        = f.text_field :title
        = f.label :body, 'Text'
        = f.text_area :body
        = f.submit 'Save'
.comments
  -@question.comments.each do |c|
    = render partial:'comments/comment', locals: { comment: c }
  = link_to 'Add comment','', class: 'new-comment-link', data: { commentable_id: @question.id }

  =form_for [@question, @question.comments.build], remote: true, html: { id: "new-comment-#{@question.id}"} do |f|
      = f.label :comment_body, "Comment"
      = f.text_area :comment_body
      = f.submit 'Save'

.answers
  = render 'answers/answers'

= form_for [@question, @answer], remote: true do |f|
  p
    = f.label :body, 'Your answer'
    .answer-errors
    = f.text_area :body
  p
    =f.fields_for :attachments, @answer.attachments.build do |a|
      = render 'attachments/attachments_fields', f: a
      = link_to_add_association 'Add', f, :attachments, partial: 'attachments/attachments_fields'
  p= f.submit 'Create'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    <% @question.errors.full_messages.each do |message| %>
        $('.question-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('.question').html('<%= j render @question %>');
    $('.edit-question-link').click(function(e) {
        e.preventDefault();
    	  $('.question').hide();
    	  $('.edit_question').show();
    });
<% end %>