config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, -> (u){ u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/github' => 'omniauth_callbacks#github'
  end

  resources :attachments, only: [:destroy]

  concern :votable do
    resources :votes, only: [:up_rating, :down_rating, :unvote] do
      post :up_rating, on: :collection
      post :down_rating, on: :collection
      post :unvote, on: :collection
    end
  end


  resources :questions, concerns: :votable do
    resources :comments, only: [:create]
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: [:create]
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get :search, to:'search#index'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include ElasticMyAnalyzer
  include EsHelperAnswer
  include Attachable
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  validates :body, :user_id, presence: true

  after_create :send_new_answer
  after_create :subscribers_informer

  

  settings ES_SETTING do
    mappings dynamic: 'true' do
      indexes :body, type: 'text', analyzer: 'my_analyzer'
      indexes :searching, type: 'boolean'
    end
  end

  def best
    ActiveRecord::Base.transaction do
      best_answer = question.best_answer
      if self != best_answer
        best_answer.update!(best: false) if best_answer
        self.update!(best: true)
      end
    end
  end

  def send_new_answer
    AnswerMailer.delay.new_answer(self.question.user)
  end

  def subscribers_informer
    SubscribersSenderJob.perform_later(self)
  end

end

app/controllers/answers_controller.rb
require 'pry'
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:create]
  before_action :set_answer, only: [:destroy, :update, :best, :show]
  #after_action :publish_answer, only: [:create]
  respond_to :js, :json
  authorize_resource
  def index
  end
  def new
    @answer = Answer.new
    respond_with @answer
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge({ user: current_user })))
  end

  def update
     @answer = Answer.find(params[:id])
     @answer.update(answer_params)
     @question = @answer.question
  end

  def destroy
    if @answer.user_id == current_user.id
      respond_with @answer.destroy
    end
  end

  def best
    #respond_with(@answer.best)
    @answer.best #if current_user.author_of?(@question)
    @answers = @answer.question.answers
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast 'answers', ApplicationController.render(partial: 'answers/answers', locals: { question: @answer.question })
  end
  def load_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:id, :body, attachments_attributes: [:file, :id, :_delete])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  def index
    @question = Question.find(params[:question_id])
    respond_with @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: AnswerSerializer
  end

  def create
    @question = Question.find(params[:question_id])
    respond_with @question.answers.create(answer_params.merge(user: current_resource_owner))
  end

  private
  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answers.html.slim
- @question.answers.order(best: :desc).each do |answer|
  - if answer.persisted?
    div class=('best-answer' if answer.best?) 
      p= answer.body
      = render partial: 'votes/vote', locals: {type: 'answer', votable: answer}
      ul 
      - answer.attachments.each do |a|
        li id="attachment-id-#{a.id}"
        li= link_to a.file.identifier, a.file.url
        - if user_signed_in? && current_user.author_of?(answer)
          br
          =link_to 'Delete', attachment_path(a), method: :delete, remote: true
      - if user_signed_in? && current_user.author_of?(@question)
        - if answer.best?
          h6= 'The best answer!'
        - else
          p= link_to 'Best', best_answer_path(answer), method: :patch, remote: true    
  - if user_signed_in? && current_user.author_of?(answer)
      p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      p= link_to 'Remove', answer_path(answer), method: :delete, remote: true
      p
      = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, "Answer"
        = f.text_area :body
        = f.submit 'Save'
  .comments
    -answer.comments.each do |c|
      = render partial:'comments/comment', locals: { comment: c }
    = link_to 'Add comment','', class: 'new-comment-link', data: { commentable_id: answer.id }
    
    =form_for [answer, answer.comments.build], method: :post, remote: true, html: { id: "new-comment-#{answer.id}"} do |f|
        = f.label :comment_body, "Comment"
        = f.text_area :comment_body
        = f.submit 'Save'

app/views/answers/best.js.erb
$('.answers').html('<%= j render "answers/answers" %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
    $('.answers').html('<%= j render 'answers/answers' %>');
    $('textarea#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
      $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
  $('#answer_<%= @answer.id %>').remove();
  $('.answers').html('<%= j render 'answers/answers' %>');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('.answers').html('<%= j render 'answers/answers' %>');
    $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
    });
<% end %>