config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, -> (u){ u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/github' => 'omniauth_callbacks#github'
  end

  resources :attachments, only: [:destroy]

  concern :votable do
    resources :votes, only: [:up_rating, :down_rating, :unvote] do
      post :up_rating, on: :collection
      post :down_rating, on: :collection
      post :unvote, on: :collection
    end
  end


  resources :questions, concerns: :votable do
    resources :comments, only: [:create]
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: [:create]
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get :search, to:'search#index'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QA</title>
   <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "QA" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= action_cable_meta_tag%>
    <%= include_gon(watch: true) %>

  <!--<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  </head>-->

  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">QA</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <% if user_signed_in? %>
                <%= link_to "Выйти", destroy_user_session_path, method: :delete %>
            <% else %>
                <%= link_to "Войти", new_user_session_path  %>
            <% end %>
            <%= link_to "Questions", questions_path %>
            <%= form_tag '/search', method: 'GET' do %>
              <%= label_tag(:query, "Search for:") %>
              <%= text_field_tag(:query, params[:query]) %>
              <%= submit_tag("Search") %>
            <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>


      </div><!--/row-->

      <footer>
        <p>&copy; Учебный проект М.В.Зуев 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>